import type { Metadata } from 'next';
import { Poppins as FontSans } from 'next/font/google';
import '@/app/styles/globals.css';
import StarCanvas from './components/canvas/starCanvas';

const fontSans = FontSans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-sans',
});
export const metadata: Metadata = {
  title: 'Bhavya Jain | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} overflow-x-hidden overflow-y-scroll bg-[#030014]`}
      >
        <StarCanvas />
        {children}
      </body>
    </html>
  );
}
